---
version: "3.3"

services:

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443

  heroguessr_1:
    build: ./HeroGuessr1/
    restart: always
    ports:
      - "5000:80"

  heroguessr_2:
    build: ./HeroGuessr2/
    restart: always
    ports:
      - "5001:80"