---
version: "3.3"

services:

  generator:
    build:
      context: ./Generator/
    environment:
      - LISTEN_PORT=8000
    ports:
      - "8000:8000"

  impossible:
    build:
      context: ./Impossible/
    environment:
      - LISTEN_PORT=8001
    ports:
      - "8001:8001"
