---
version: "3.3"

services:

  deadalus:
    build:
      context: ./deadalus/
    environment:
      - LISTEN_PORT=7000
    ports:
      - "7000:7000"

  heist:
    build:
      context: ./heist/
    environment:
      - LISTEN_PORT=7001
    ports:
      - "7001:7001"
