---
version: '3'

services:

  backdoor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: backdoor
    container_name: backdoor
    ports:
      - "3000:3000"
      - "80:80"