---
version: "3.3"

services:

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - smallmistake

  smallmistake:
    build: ./SmallMistakeBigMistake/
    restart: always
    environment:
      - PORT=5000
      - FLAG=Hero{Sm4ll_Mist4ke_c4n_be_d4ngerous_10853085}
    ports:
      - "5000:5000"
    cpus: 1
    mem_limit: 2048m
