---
version: "3.3"

services:

  nginx:
    image: nginx:1.21
    restart: always
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - smallmistake
      - blackcat
      - flowercdn

  # --- smallmistake ---
  smallmistake:
    build: ./SmallMistakeBigMistake/
    restart: always
    environment:
      - PORT=5000
      - FLAG=Hero{Sm4ll_Mist4ke_c4n_be_d4ngerous_10853085}
    ports:
      - "5000:5000"

  # --- wherebackdoor ---
  wherebackdoor:
    build:
      context: ./whereBackdoor/
      dockerfile: Dockerfile
    restart: always
    hostname: backdoor
    container_name: backdoor
    ports:
      - "3000:3000"

  # --- blackcat ---
  bot:
    build:
      context: ./BlackCat/bot/
      dockerfile: Dockerfile
    restart: always
    container_name: blackcat_bot

  blackcat:
    build:
      context: ./BlackCat/appli/
      dockerfile: Dockerfile
    restart: always
    container_name: blackcat_appli
    ports:
      - "20090:80"

  blackcatbdd:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: blackcat_bdd
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=evilhackerz
      - MYSQL_PASSWORD=wjKNQJLSP4X3uPL522Q6
      - MYSQL_DATABASE=blackcat
    volumes:
      - "./BlackCat/bdd/:/docker-entrypoint-initdb.d/"

  # --- flowercdn ---
  internalapi:
    build:
      context: ./FlowerCDN/internal_search_api/
      dockerfile: Dockerfile
    restart: always
    hostname: internal_search_api
    container_name: flowercdn-internal_search_api
    networks:
      - flowerinternal

  flowercdn:
    build:
      context: ./FlowerCDN/flowercdn/
      dockerfile: Dockerfile
    restart: always
    hostname: flowercdn
    container_name: flowercdn-site
    ports:
      - "20080:80"
    networks:
      - flowerinternal
      - default

  sql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: flowercdn-bdd
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=flower
      - MYSQL_PASSWORD=wjobQwN4X3uwT6zE
      - MYSQL_DATABASE=flowercdn
    volumes:
      - "./FlowerCDN/bdd/:/docker-entrypoint-initdb.d/"
    networks:
      - flowerinternal

networks:
  flowerinternal:
    internal: true